# The master date to use in the time series. The time of the acquisition is used
# to fetch weather data. This should be formatted as an ISO8601 date and time.
master_date: 2016-06-23T17:55:00Z

# The SLC dates to include in the time series. The master date is automatically
# included. If this key isn't included, all dates will be used.
dates:
  - 2016-06-13
  - 2016-07-23

# The locations of files and directories used in the processing steps.
files:
  # The directory where unwrapped interferograms are stored.
  uifg_dir: ./uifg
  # The directory where the output of the processing steps is saved.
  scratch_dir: .
  # The directory containing weather radar images sorted into subdirectories by
  # Year/Month/YYYYMMDDHHMM
  wr_dir: ./weather_radar
  # Path to a digital elevation model covering the interferogram region.
  dem: ./dem.nc
  # A 3-column file containing the master date, slave date and the perpendicular
  # baseline (master-slave)
  baselines: ./baselines.txt

# Define the study region by a bounding box. If this setting isn't included the
# entire region of the interferograms will be used.
region:
  lat_min: -12
  lat_max: 12
  lon_min: 15
  lon_max: 40

# The grid resolution to resample the interferograms to in metres. If this
# option is missing, no resampling is performed.
resolution:
  delta_x: 0
  delta_y: 0

# The verbosity of logging. One of CRITICAL, ERROR, WARNING, INFO or DEBUG. If
# this key isn't included, defaults to WARN.
log_level: WARN
